<?php

namespace MaterialBundle\Repository;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends \Doctrine\ORM\EntityRepository
{
    //Méthode permettant d'obtenir tout les outils en stock
	public function get_all_materials(){
		$result = $this->createQueryBuilder("mat")
					   ->where("mat.soldOut = 0")
					   ->getQuery()
					   ->getResult();
		return $result;
	}

	/**
	 * Méthode permettant d'obtenir les outils en rupture de stock
	 */
	public function get_sold_out_materials(){
		$result = $this->createQueryBuilder("mat")
					   ->where("mat.soldOut = 1")
					   ->getQuery()
					   ->getResult();
		return $result;
	}
}
