<?php

namespace MaterialBundle\Repository;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends \Doctrine\ORM\EntityRepository
{
    //Méthode permettant d'obtenir tout les outils de l'utilisateur
	public function get_all_materials(){
		$qb = $this->createQueryBuilder('u');
		$query = $qb->select('u')
		->getQuery();
		$result = $query->getResult();
		return $result;
	}
}
